### ISSUE TITLE
update all clis to latest version for v6.4.4

### ISSUE THREAD

**Issue by ric03uec** [dry-dock/u16#125]
- https://github.com/Shippable/pm/issues/10515

I updated CLI Packages current version to latest version 

| CLI Packages  | Current Version  | Latest Version   | Link for Latest releases |
|---|---|---|---|
|  Aws-CLI | 1.11.164 | 1.14.64  | https://github.com/aws/aws-cli/releases |
|  Awebcli | 3.11.0  | 3.12.4  | https://pypi.python.org/pypi/awsebcli/3.10.0 |
|  Azure-CLI | 2.0.25  |2.0.*   |  https://github.com/Azure/azure-cli/releases |

**Comment by vijayreddy1991** [comment]
Verified the latest versions of CLI

![image](https://user-images.githubusercontent.com/31643910/38015561-c9177bbc-3289-11e8-8715-3382cc5d5a95.png)

**Comment by ric03uec** [comment]
@vijayreddy1991 can you first add a list of all the packages that were upgraded in the issue description. i'll close the issue after that

**Comment by vijayreddy1991** [comment]
I updated please take a look at it

**Comment by ric03uec** [comment]
ok. looks good. closing this now

**Comment by vijayreddy1991** [comment]
I updated  latest release version links for CLI Packages

**Comment by vijayreddy1991** [comment]
I updated the patch version for Azure-cli
