### ISSUE TITLE
update all packages to latest version for v6.4.4

### ISSUE THREAD

**Issue by ric03uec** [dry-dock/u16#126]
- https://github.com/Shippable/pm/issues/10515

packages | current version | update version | Link for latest releases |
-- | -- | -- |--
Git | 2.16.2 |no update |https://launchpad.net/~git-core/+archive/ubuntu/ppa
gcloud | 173.0.0-0 | 194.0.0|https://cloud.google.com/sdk/docs/release-notes
kubectl | 1.8.0 | 1.9.0|https://kubernetes.io/docs/imported/release/notes/
KOPS | 1.8.0 | 1.8.1|https://github.com/kubernetes/kops/releases
helm | v2.8.0 | v2.8.2 |https://github.com/kubernetes/helm/releases
doctl | 1.6.0 | 2.3.2|https://github.com/digitalocean/netbox/releases
ansible | 2.3.0.0 | 2.4.3.0|https://github.com/ansible/ansible/releases?after=v2.5.0a1
boto | 2.46.1 | 2.48.0|http://boto.cloudhackers.com/en/latest/
boto3 | 1.5.15 | 1.6.16|https://github.com/boto/boto3/releases
apache-libcloud | 2.0.0 | 2.3.0|https://libcloud.apache.org/downloads.html
azure | 2.0.0 | 3.0.0|https://docs.microsoft.com/en-us/azure/app-service/azure-sdk-dotnet-release-notes-3-0
dopy | 0.3.7a | no update |https://pypi.python.org/pypi/dopy/0.3.7
terraform | 0.8.7 | 0.11.5|https://github.com/hashicorp/terraform/releases
packer | 1.1.0 | 1.2.2|https://www.packer.io/downloads.html
jfrog | 1.7.0 | 1.14.0|https://bintray.com/jfrog/jfrog-cli-go/jfrog-cli-windows-amd64#release
zip | -| 3.0|https://packages.ubuntu.com/xenial/zip

also add a new package that is zip=3.0* \

**Comment by bindushree16** [comment]
i am working on this .unable to assingn myself as i dont have access

**Comment by ric03uec** [comment]
@bindushree16 can you add a list of all packages that are getting updated in the issue description here

**Comment by ric03uec** [comment]
@bindushree16 we also need to add `zip` package in the list of core packages

**Comment by bindushree16** [comment]
![image](https://user-images.githubusercontent.com/37651858/38024441-a7a1c30c-32a2-11e8-8564-4a1a883eb034.png)

i verified the packages

**Comment by ric03uec** [comment]
why did we not update packer? the latest version is 1.2.2

**Comment by ric03uec** [comment]
helm is also updated to 2.8.2 (https://github.com/kubernetes/helm/releases)

**Comment by bindushree16** [comment]
i update the latest versions

**Comment by bindushree16** [comment]
![image](https://user-images.githubusercontent.com/37651858/38072552-7c9e9e12-3344-11e8-9e6a-9a5f79077e10.png)

i verified the packages

**Comment by bindushree16** [comment]
build success
https://app.shippable.com/github/Shippable/jobs/x86_64_Ubuntu_16_04_prep/builds/5abcbb344a24a20700a20e7b/console
