### ISSUE TITLE
update all languages to latest version for v6.4.4

### ISSUE THREAD

**Issue by ric03uec** [dry-dock/u16#127]
- https://github.com/Shippable/pm/issues/10515

- Updating following language versions 

#### Node

|  package | current version |update version |
|----------------|---------------|-----------------|
|  yarn  |   1.2.1-1   |   1.5.1-1  |

#### Ruby

|  package | current version |update version |
|-----------------|-------------|--------|
| ruby |    2.3.5   |   2.4.1  |

**Comment by ric03uec** [comment]
@Ranjansingh41 can you update the list of all the languages that are getting updated in the issue description

**Comment by ric03uec** [comment]
@Ranjansingh41 why are we not updating the nodejs version?

**Comment by Ranjansingh41** [comment]
U16 Base image Build is sucess   https://app.shippable.com/github/Shippable/jobs/x86_64_Ubuntu_16_04_prep/builds/5abcbb344a24a20700a20e7b/console
